#! /bin/bash

case $# in
    0) cat <<EOF
Inscrute des croix dans une image
usage: ./croix imagefond imagepoints imagesortie
EOF
	exit ;;
esac

cat > cross55 <<EOF
0 -2
0 -1
0 1
0 2
-2 0 
-1 0
1 0
2 0
EOF

# Croix rouge
raz $(par $1 -x -y) -v 3 > cross
ero  -di $2 -f cross55 | cco -f | melg - cross

# Croix rouge incrusté dans l'image
cnvcol -cv $1 > $3
melg cross -tr $3

rm -f cross55 cross 





